config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:index,:show]
  root 'tops#index'
  resources :events do
    collection do
      post :confirm
      get :parthicipation_events
      get :favorite
      get :current_user_events
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :favorites,only:[:create,:destroy]
  resources :participations,only:[:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  has_many :favorites, dependent: :destroy
  has_many :favorite_events, through: :favorites, source: :event
  has_many :participations,dependent: :destroy
  has_many :participation_events, through: :participations, source: :event
  has_many :active_relationships, foreign_key: 'follower_id',class_name: 'Relationship',dependent: :destroy
  has_many :passive_relationships,foreign_key: 'followed_id',class_name: 'Relationship',dependent: :destroy
  has_many :following,through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :events  
  mount_uploader :image,ImageUploader
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  validates :username,presence: true,length:{maximum:30}
  validates :email, format:{with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  before_validation { email.downcase! }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show,:index]
  def index
    @users = User.all
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
    @favorites = current_user.favorites
  end

private

  def user_params
    params.require(:user).permit(:image,:image_cache)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
  <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
    <%= f.hidden_field :followed_id %>
    <%= f.submit "フォロー" %>
  <% end %>
  <% else %>
  <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),method: :delete) do |f| %>
    <%= f.submit "フォロー解除" %>
  <% end %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>ユーザー リスト</h1>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @q, url: :users do |f| %>
          <%= f.label :username %>
          <%= f.text_field :username_cont, placeholder: '名前' %>
          <br>
          <%= f.submit 'SEARCH' %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <% @users.each do |user| %>
        <div class="col-xs-12 col-sm-6 col-md-6 event-panel-primary">
            <div class="flex-box">
              <ul class="media-list">
                <li class="media">
                  <div class="media-left">
                    <% if user.image.url %>
                      <div class="media-object">
                        <%= image_tag(user.image.url,:size => "75x75") %>
                      </div>
                    <% end %>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading"><%= link_to user.username, user %></h4>
                      <% if user != current_user %>
                        <%= render 'follow_form', user: user %>
                      <% end %>
                  </div>
                </li>
              </ul>
            </div>
        </div>
      <% end %>
    </div>
    <div class="row pagenate">
      <%= paginate(@users) %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">
  <% if @user.id == current_user.id %>
    <h1>あなたの詳細ページ</h1>
    <div class="row_A">
        <div class="col-sm-12 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              プロフィール
            </div>
            <div class="event_title col-md-12">
              <p>メールアドレス:<%= current_user.email %></p>
            </div>
            <div class="event_title col-md-12">
              <p>お名前:<%= current_user.username %></p>
            </div>
          </div>
        </div>
      <div class="col-md-6">
        <p id="notice"><%= notice %></p>
          <% if @user.image.url %>
            <p><strong>Image:</strong>
               <%= image_tag(@user.image.url,:size => "300x300") %></p>
          <% end %>
      </div>
    </div>
    <div class="row_B">
      <div class="col-sm-12 col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            フォローしているユーザー
          </div>
          <% @user.following.each do |follow| %>
            <tr>
              <% if follow.image.url %>
                <td><%= image_tag(follow.image.url,:size => "75x75") %></td>
              <% end %>
              <td><%= link_to follow.username,user_path(follow.id) %></td>
            </tr>
          <% end %>
          <br>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            フォローされているユーザー
          </div>
          <% @user.followers.each do |follower| %>
            <tr>
              <% if follower.image.url %>
                <td><%= image_tag(follower.image.url,:size => "75x75") %></td>
            　<% end %>
                <td><%= link_to follower.username,user_path(follower.id) %></td>
            </tr>
          <% end %>
          <br>
        </div>
        <div class="row_C">
          <ul>
            <li class="col-md-6"><%= link_to 'プロフィール編集', edit_user_registration_path,class: 'btn btn-info' %></li>
            <li class="col-md-6"><%= link_to "参加するイベント一覧", parthicipation_events_events_path, class: 'btn btn-info' %></li
            <li class="col-md-6"><%= link_to "企画イベント一覧", current_user_events_events_path, class: 'btn btn-info' %></li>
            <li class="col-md-6"><%= link_to "お気に入り一覧", favorite_events_path, class: 'btn btn-info' %></li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <h1><%= @user.username %>さんの詳細ページ</h1>
  <% end %>

  <br>
</div>