config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:index,:show]
  root 'tops#index'
  resources :events do
    collection do
      post :confirm
      get :parthicipation_events
      get :favorite
      get :current_user_events
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :favorites,only:[:create,:destroy]
  resources :participations,only:[:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :participations, dependent: :destroy
  has_many :participation_users, through: :participations, source: :user

  mount_uploader :image,ImageUploader

  validate :time_cannot_be_in_the_past, :time_cannot_be_later_than_end_datetime
  validate :add_error_image
  validates :title, :time, :endtime, :place, :capacity, :content, presence: true
  validates :title, length: { in: 1..30 }
  validates :capacity, numericality: { greater_than_or_equal_to: 0 }

 private

  def time_cannot_be_in_the_past
    if time.present? && time < Date.today
      errors.add(:time,"は今日より過去は設定できません")
    end
  end

  def time_cannot_be_later_than_end_datetime
    if time.present? && time > endtime
      errors.add(:time,"は終了日より後に設定できません")
    end
  end

  def add_error_image
  # imageが空のときにエラーメッセージを追加する
    if image.blank?
      errors[:base] << "画像を選択してください"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only:[:show,:edit,:update,:destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :show,:destroy]
  before_action :require_login_current,only:[:edit,:destroy]

  def index
    @events = Event.all
    @index_title = "イベント一覧"
    @q = Event.ransack(params[:q])
    @events = @q.result.page(params[:page]).per(8)
  end

  def new
    if params[:back]
      @event = Event.new(event_params)
    else
      @event = Event.new
    end
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path, notice:"イベントを作成しました"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(event_id: @event.id)
    @participation = current_user.participations.find_by(event_id: @event.id)
  end

  def edit

  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice:"イベントを編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice:"イベントを削除しました"
  end

  def confirm
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    render :new if @event.invalid?
  end

  # def list
  #   if params[:id] == "join"
  #     joins = Participation.where(user_id: current_user.id)
  #     @events = Array.new
  #     joins.each do |join|
  #       @events << join.event
  #     end
  #
  #     @events = @events.page(params[:page]).per(8)
  #     @index_title = "参加するイベント"
  #
  #   elsif params[:id] == "own"
  #     @events = Event.where(user_id: current_user.id).page(params[:page]).per(8)
  #     @index_title = "企画したイベント"
  #
  #   elsif params[:id] == "favorite"
  #     favorites = Favorite.where(user_id: current_user.id)
  #     @events = Array.new
  #     favorites.each do |favorite|
  #       @events << favorite.event
  #     end
  #     @index_title = "お気に入りしたイベント"
  #   else
  #     redirect_to events_path
  #     @index_title = "イベント一覧"
  #   end
  #   render :index
  # end

  def current_user_events
    @current_user_events = current_user.events
    @events = current_user.events.page(params[:page]).per(8)
  end

  def favorite
    @favorites = current_user.favorite_events
    @events = current_user.favorite_events.page(params[:page]).per(8)
  end

  def parthicipation_events
    @parthicipation_events = current_user.participation_events
    @events = current_user.participation_events.page(params[:page]).per(8)
  end

  private

  def event_params
    params.require(:event).permit(:title,:time,:endtime,:place,:capacity,:content,:username,:image,:image_cache)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def require_login_current
    unless current_user.id == @event.user_id
      redirect_to events_path,notice:"その他のユーザーです"
    end
  end

  def user_params
    params.require(:user).permit(:image,:image_cache)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/views/events/_form.html.erb
<div class="container">
  <%= form_with(model: @event,local: true, url: choose_new_or_edit) do |form| %>
    <% if @event.errors.any? %>
      <div class="error_explanation alert alert-error alert alert-danger" role="alert">
        <h2><%= @event.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-horizontal">
      <div class="row">
        <div class="col-md-4">
          <div class="row_A">
            <div class="panel panel-default">
              <div class="panel-heading">
                入力内容
              </div>
              <div class="event_title col-md-12 ">
                <%= form.label :タイトル,class:"control-label" %>
                <%= form.text_field :title %>
              </div>
              <div class="start_time col-md-12">
                <%= form.label :開始日時,class:"control-label" %>
                <%= form.text_field :time, :class => 'datepicker' %>
              </div>
              <div class="end_time col-md-12">
                <%= form.label :終了日時,class:"control-label" %>
                <%= form.text_field :endtime, :class => 'datepicker' %>
              </div>
              <div class="event_place col-md-12">
                <%= form.label :会場名, class:"control-label" %>
                <%= form.text_field :place %>
              </div>
              <div class="event_capacity col-md-12">
                <%= form.label :定員, class:"control-label" %>
                <%= form.number_field :capacity %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="row_B">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= form.label :画像 %>
              </div>
              <%= image_tag(@event.image.url,:size => "500x480") if @event.image.url %>
              <%= form.file_field :image %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="event_content col-md-12">
          <%= form.label :詳細内容 %>
          <%= form.text_area :content,class:"form-control", id:"InputTextarea" %>
        </div>
      </div>
    </div>
    <br>
    <div class="submit_btn">
    <%= form.submit class: 'btn btn-info'%>
    </div>
  <% end %>
  <br>

  <!-- <div class="link_btn">
      <%= link_to "イベント一覧",events_path, class: 'btn btn-info'%>
  </div> -->

</div>

app/views/events/confirm.html.erb
<h3>"以下の内容で、送信する"</h3>
<div class="container">
  <%= form_with(model: @event,url: events_path,local: true)do |form| %>
    <div class="form-horizontal">
      <div class="row">
        <div class="col-md-4">
          <div class="row_A">
            <div class="panel panel-default">
              <div class="panel-heading">
                入力内容
              </div>
              <div class="event_title col-md-12">
                <%= form.label :タイトル,class:"control-label" %>
                <p><%= @event.title %></p>
                <%= form.hidden_field :title %>
              </div>
              <div class="start_time col-md-12">
                <%= form.label :開始日時,class:"control-label" %>
                <p><%= @event.time %></p>
                <%= form.hidden_field :time %>
              </div>
              <div class="end_time col-md-12">
                <%= form.label :終了日時,class:"control-label" %>
                <p><%= @event.endtime %></p>
                <%= form.hidden_field :endtime %>
              </div>
              <div class="event_place col-md-12">
                <%= form.label :会場名, class:"control-label" %>
                <p><%= @event.place %></p>
                <%= form.hidden_field :place %>
              </div>
              <div class="event_capacity col-md-12">
                <%= form.label :定員, class:"control-label" %>
                <p><%= @event.capacity %></p>
                <%= form.hidden_field :capacity %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="row_B">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= form.label :画像 %>
              </div>
              <%= image_tag(@event.image.url,:size => "500x480") if @event.image.url %>
              <%= form.hidden_field :image_cache %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="event_content col-md-12">
          <%= form.label :詳細内容 %>
          <%= form.hidden_field :content %>
          <%= form.text_area :content,class:"form-control", id:"InputTextarea" %>
        </div>
      </div>
    </div>
    <br>
    <div class="submit_btn">
      <%= form.submit class: 'btn btn-info'%>
    </div>
    <br>
<% end %>

<%= form_with(model: @event, url: new_event_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :time %>
  <%= form.hidden_field :endtime %>
  <%= form.hidden_field :place %>
  <%= form.hidden_field :capacity %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit '戻る', name: 'back' %>
<% end %>
</div>
<br>

app/views/events/current_user_events.html.erb
<h1>企画したイベント</h1>
<div class="container">
  <% unless @current_user_events.present? %>
  <br>
  <p>企画したイベントはありません。</p>
  <% else %>
  <div class="row">
    <% @current_user_events.each do |event| %>
      <div class="col-xs-12 col-sm-6 col-md-6 event-panel-primary">
        <h2><%= event.title %></h2>
        <h3><%= event.user.username %></h3>
        <%= link_to "詳細確認",event_path(event.id),class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <% end %>
  <br>
  <div class="row pagenate">
    <%= paginate(@events) %>
  </div>
    <%= link_to '戻る', events_path,class: "btn btn-outline-secondary" %>
</div>

app/views/events/edit.html.erb
<h2><strong>イベントを編集する</strong></h2>

<%= render 'form' %>

app/views/events/favorite.html.erb
<h1>お気に入りのイベント</h1>
  <div class="container">
    <% unless @favorites.present? %>
  <br>
  <p>お気に入りのイベントはありません。</p>
  <% else %>
  <div class="row">
    <% @favorites.each do |event| %>
      <div class="col-xs-12 col-sm-6 col-md-6 event-panel-primary">
        <h2><%= event.title %></h2>
        <h3><%= event.user.username %></h3>
        <%= link_to "詳細確認",event_path(event.id),class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <% end %>
  <br>
  <div class="row pagenate">
    <%= paginate(@events) %>
  </div>
  <br>
    <%= link_to '戻る', events_path,class: "btn btn-outline-secondary" %>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1><%= @index_title %></h1>
    <div class="new-event">
      <%= link_to 'イベント新規作成',new_event_path,class: 'btn btn-primary' %>
    </div>
    <div class="row event-serch">
      <% if params[:id] == nil %>
        <%= search_form_for @q do |f| %>
          <%= f.label :検索 %>
          <%= f.text_field :title_or_place_cont, placeholder: 'イベント名or開催地' %>
          <%= f.submit 'SEARCH' %>
        <% end %>
      <% end %>
    </div>
    <div class="contents">
      <div class="row center-block" >
        <% @events.each do |event| %>
          <div class="card-deck col-sm-6 col-md-4" >
            <div class="card img-thumbnail">
              <%= link_to event,class: "event_link" do %>
                <% if event.image.url %>
                  <%= image_tag(event.image.url,:size => "250x250",class: "card-img-top") %>
                <% end %>
                <div class="card-body">
                  <% if event.time <= Time.now %>
                    <h4 class="card-title">タイトル：<%= event.title.truncate(20) %></h4>
                    <h4 class="alert alert-warning">このイベントは終了致しました</h4>
                  <% else %>
                    <h4 class="card-title">タイトル：<%= event.title.truncate(20) %></h4>
                    <hr>
                    <strong><p class="card-text"><%= event.time%></p></strong>
                    <h4><%= event.user.username %></h4>
                  <% end %>
                </div>
              <% end %>
              <% if current_user.present? %>
                <%= link_to "詳細確認",event_path(event.id),class: 'btn btn-default' %>
                <% if current_user.id == event.user_id %>
                  <%= link_to "編集",edit_event_path(event.id), class: 'btn btn-info' %>
                  <%= link_to '削除する',event_path(event.id), data: {confirm: "本当に削除していいんですか？"}, method: :delete,class: 'btn btn-danger'%>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row pagenate">
      <%= paginate(@events) %>
    </div>
</div>

app/views/events/new.html.erb
<h2>イベントを作成する</h2>

<%= render 'form' %>

app/views/events/parthicipation_events.html.erb
<h1>参加予定のイベント</h1>
<div class="container">
  <% unless @parthicipation_events.present? %>
  <br>
    <p>参加予定のイベントはありません。</p>
  <% else %>
  <div class="row">
    <% @parthicipation_events.each do |event| %>
      <div class="col-xs-12 col-sm-6 col-md-6 event-panel-primary">
        <h2><%= event.title %></h2>
        <h3><%= event.user.username %></h3>
        <%= link_to "詳細確認",event_path(event.id),class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <% end %>
  <div class="row pagenate">
    <%= paginate(@events) %>
  </div>
  <br>
    <%= link_to '戻る', events_path,class: "btn btn-outline-secondary" %>
</div>

app/views/events/show.html.erb
<h1>イベント詳細画面</h1>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="row_A">
        <div class="panel panel-default">
          <div class="panel-heading">
            入力内容
          </div>
          <div class="event_title col-md-12 p-2">
            <p>タイトル:<%= @event.title %></p>
          </div>
          <div class="start_time col-md-12">
            <p>開始日時:<%= @event.time %></p>
          </div>
          <div class="end_time col-md-12">
            <p>終了日時:<%=@event.endtime %></p>
          </div>
          <div class="event_place col-md-12">
            <p>会場名:<%= @event.place %></p>
          </div>
          <div class="event_capacity col-md-12">
            <p>定員:<%=@event.capacity %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="row_B">
        <div class="panel panel-default">
          <div class="panel-heading">
            画像
          </div>
            <%= image_tag(@event.image.url,:size => "500x480") if @event.image.url %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="event_content col-md-12">
      <table>
        <tbody>
          <tr>
            <th>詳細内容: </th>
            <td><%= simple_format(h(@event.content),{},sanitize: false, wrapper_tag: "div" )%></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="select_btns">
    <% unless @event.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(event_id: @event.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
      <% if @event.time <= Time.now %>
        <h4 class="alert alert-warning">このイベントは終了致しました</h4>
      <% else %>
        <% if @participation.present? %>
          <%= link_to 'イベントをキャンセルする', participation_path(id: @participation.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'イベントに参加する', participations_path(event_id: @event.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br>
</div>