config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:index,:show]
  root 'tops#index'
  resources :events do
    collection do
      post :confirm
      get :parthicipation_events
      get :favorite
      get :current_user_events
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :favorites,only:[:create,:destroy]
  resources :participations,only:[:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Chronometer</title>
    <%= csrf_meta_tags %>
  </head>
<div class="wapper">
  <body>
    <header>
      <div class="site-logo">
        <%= link_to "Chronometer",root_path %>
      </div>
      <nav class="navbar navbar-default">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">メニュー</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to "イベント一覧", events_path %></li>
              <li><%= link_to 'ユーザーリスト', users_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "新規ユーザー登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>


    </header>
    <% if notice %>
      <p class="alert alert-notice alert alert-success" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error alert alert-danger" role="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
    <br>
    <footer>
      <p>作成者 折原龍太</p>
      <p>© 2018-2020 Copyright Ryuta Orihara.</p>
    </footer>
  </body>
</div>
</html>